// ---------- Локализации ----------
const locales = {
  ru: {
    "brand-title": "GlobalAstro",
    "question-label": "Какой ваш вопрос астрологу?",
    "ask-btn": "Получить ответ",
    "me-title": "Мои данные",
    "partner-title": "Данные партнёра",
    "options-title": "Дополнительные опции",
    "result-default": "",
    "modal-me-title": "Мои данные",
    "me-dob-label": "Дата рождения",
    "me-place-label": "Место рождения",
    "me-gender-label": "Пол",
    "me-time-label": "Время рождения",
    "me-save-btn": "Сохранить",
    "me-cancel-btn": "Отмена",
    "modal-partner-title": "Данные партнёра",
    "p-name-label": "Имя",
    "p-dob-label": "Дата рождения",
    "p-place-label": "Место рождения",
    "p-gender-label": "Пол",
    "p-time-label": "Время рождения",
    "partner-save-btn": "Сохранить",
    "partner-cancel-btn": "Отмена",
    "modal-options-title": "Дополнительные опции",
    "opt-num-label": "Нумерология",
    "opt-taro-label": "Таро",
    "opt-china-label": "Китайский гороскоп",
    "opt-more-label": "Ещё",
    "options-save-btn": "Сохранить",
    "options-cancel-btn": "Отмена",
    "me-gender-male": "Мужской",
    "me-gender-female": "Женский",
    "p-gender-male": "Мужской",
    "p-gender-female": "Женский",
    "partner-summary-empty": "—",
    "me-summary-empty": "—",
    "question-placeholder": [
      "Покупать мне BMW X5 на следующей неделе?",
      "Ждать ли повышения в этом месяце?",
      "Встретится ли любовь в этом году?",
      "Стоит ли менять работу сейчас?",
      "Как улучшить отношения с партнёром?",
      "Куда поехать в отпуск летом?",
      "Что ожидает в финансовой сфере?",
      "Нужен ли мне переезд в другой город?",
      "Получится ли сдать экзамен?",
      "Чего ждать от нового проекта?",
      "Будет ли успешна сделка?",
      "Стоит ли начинать бизнес?",
      "Когда лучше выходить замуж?",
      "Какие риски в ближайшее время?",
      "Чего избегать в следующем месяце?",
      "Какой знак зодиака мне подходит?",
      "Чего ждать от партнёра?",
      "Переезжать ли мне за границу?",
      "Стоит ли доверять новому знакомому?",
      "Как пройдут ближайшие недели?"
    ]
  },
  en: {
    "brand-title": "GlobalAstro",
    "question-label": "What is your question to the astrologer?",
    "ask-btn": "Get answer",
    "me-title": "My data",
    "partner-title": "Partner data",
    "options-title": "Additional options",
    "result-default": "",
    "modal-me-title": "My data",
    "me-dob-label": "Date of birth",
    "me-place-label": "Place of birth",
    "me-gender-label": "Gender",
    "me-time-label": "Time of birth",
    "me-save-btn": "Save",
    "me-cancel-btn": "Cancel",
    "modal-partner-title": "Partner data",
    "p-name-label": "Name",
    "p-dob-label": "Date of birth",
    "p-place-label": "Place of birth",
