// ---------- Локализация (многоязычие) -----------
const langs = [
  {code:"ru", label:"🇷🇺 Русский"},
  {code:"en", label:"🇬🇧 English"},
  {code:"es", label:"🇪🇸 Español"},
  {code:"pt", label:"🇵🇹 Português"},
  {code:"de", label:"🇩🇪 Deutsch"},
  {code:"fr", label:"🇫🇷 Français"},
  {code:"sr", label:"🇷🇸 Српски"},
  {code:"pl", label:"🇵🇱 Polski"},
  {code:"ar", label:"🇸🇦 العربية"},
  {code:"zh", label:"🇨🇳 中文"},
];

const labels = {
  ru: {
    qLbl: "Какой Ваш вопрос астрологу?",
    me: "Мои данные",
    partner: "Данные партнёра",
    opts: "Дополнительные опции",
    ask: "Получить ответ",
    ex: [
      "Покупать мне BMW X5 на следующей неделе?",
      "Что ждёт меня в отношениях с новым партнёром?",
      "Как будет складываться моя карьера в этом году?",
      "Когда лучше начинать новое дело?",
      "Стоит ли соглашаться на переезд?",
      "Какие энергии месяца для меня наиболее важны?",
      "В какой сфере меня ждёт успех в ближайшее время?",
      "Как будут складываться отношения с детьми?",
      "Есть ли вероятность встретить любовь в этом месяце?",
      "Подходит ли мне выбранная профессия?",
      "Когда ждать повышения на работе?",
      "Стоит ли инвестировать в недвижимость сейчас?",
      "Что скажет гороскоп о моём здоровье?",
      "Появятся ли новые друзья в этом году?",
      "Нужно ли мне менять сферу деятельности?",
      "Есть ли опасность крупных трат в этом месяце?",
      "Когда лучше планировать отпуск?",
      "Смогу ли я реализовать творческий проект?",
      "Какая дата удачна для подписания договора?",
      "Какова совместимость с моим партнёром?"
    ],
    modal: {
      me: {h: "Мои данные", dob:"Дата рождения", place:"Место рождения", gender:"Пол", time:"Время рождения (опционально)", cancel:"Отмена", save:"Сохранить"},
      partner: {h:"Данные партнёра", name:"Имя", dob:"Дата рождения", place:"Место рождения", gender:"Пол", time:"Время рождения (опционально)", cancel:"Отмена", save:"Сохранить"},
      opts: {h:"Доп. опции", num:"Нумерология", taro:"Таро", china:"Китайский гороскоп", more:"Ещё что-нибудь", cancel:"Отмена", save:"Сохранить"},
    }
  },
  en: {
    qLbl: "What is your question to the astrologer?",
    me: "My Data",
    partner: "Partner's Data",
    opts: "Additional Options",
    ask: "Get Answer",
    ex: [
      "Should I buy a BMW X5 next week?",
      "What awaits me in my relationship with a new partner?",
      "How will my career develop this year?",
      "When is the best time to start a new project?",
      "Should I accept the relocation offer?",
      "Which monthly energies are most important for me?",
      "Which area will bring me success soon?",
      "How will relationships with children go?",
      "Will I find love this month?",
      "Is my career path the right one for me?",
      "When can I expect a promotion at work?",
      "Is it a good time to invest in real estate?",
      "What does my horoscope say about my health?",
      "Will I make new friends this year?",
      "Should I change my professional field?",
      "Are large expenses a risk this month?",
      "When is the best time to plan a vacation?",
      "Will I succeed with my creative project?",
      "What is a lucky date to sign a contract?",
      "How compatible am I with my partner?"
    ],
    modal: {
      me: {h: "My Data", dob:"Date of Birth", place:"Place of Birth", gender:"Gender", time:"Time of Birth (optional)", cancel:"Cancel", save:"Save"},
      partner: {h:"Partner's Data", name:"Name", dob:"Date of Birth", place:"Place of Birth", gender:"Gender", time:"Time of Birth (optional)", cancel:"Cancel", save:"Save"},
      opts: {h:"More Options", num:"Numerology", taro:"Tarot", china:"Chinese horoscope", more:"Something else", cancel:"Cancel", save:"Save"},
    }
  },
  es: {
    qLbl: "¿Cuál es tu pregunta para el astrólogo?",
    me: "Mis datos",
    partner: "Datos de pareja",
    opts: "Opciones adicionales",
    ask: "Obtener respuesta",
    ex: [
      "¿Debo comprar un BMW X5 la próxima semana?",
      "¿Qué me espera en la relación con una nueva pareja?",
      "¿Cómo evolucionará mi carrera este año?",
      "¿Cuándo es mejor comenzar un nuevo proyecto?",
      "¿Debería aceptar la reubicación?",
      "¿Qué energías mensuales son más importantes para mí?",
      "¿En qué área tendré éxito pronto?",
      "¿Cómo serán las relaciones con los hijos?",
      "¿Encontraré el amor este mes?",
      "¿Es adecuada mi carrera?",
      "¿Cuándo esperar un ascenso?",
      "¿Es buen momento para invertir en propiedades?",
      "¿Qué dice el horóscopo sobre mi salud?",
      "¿Haré nuevos amigos este año?",
      "¿Debo cambiar de campo profesional?",
      "¿Riesgo de gastos grandes este mes?",
      "¿Cuándo es mejor planear vacaciones?",
      "¿Tendré éxito en un proyecto creativo?",
      "¿Qué fecha es afortunada para firmar contratos?",
      "¿Qué tan compatible soy con mi pareja?"
    ],
    modal: {
      me: {h: "Mis datos", dob:"Fecha de nacimiento", place:"Lugar de nacimiento", gender:"Género", time:"Hora de nacimiento (opcional)", cancel:"Cancelar", save:"Guardar"},
      partner: {h:"Datos de pareja", name:"Nombre", dob:"Fecha de nacimiento", place:"Lugar de nacimiento", gender:"Género", time:"Hora de nacimiento (opcional)", cancel:"Cancelar", save:"Guardar"},
      opts: {h:"Opciones", num:"Numerología", taro:"Tarot", china:"Horóscopo chino", more:"Algo más", cancel:"Cancelar", save:"Guardar"},
    }
  },
  pt: {
    qLbl: "Qual é a sua pergunta para o astrólogo?",
    me: "Meus dados",
    partner: "Dados do parceiro",
    opts: "Opções adicionais",
    ask: "Obter resposta",
    ex: [
      "Devo comprar um BMW X5 na próxima semana?",
      "O que me espera no relacionamento com um novo parceiro?",
      "Como será minha carreira este ano?",
      "Quando é melhor começar um novo projeto?",
      "Devo aceitar a mudança de cidade?",
      "Quais energias do mês são mais importantes para mim?",
      "Em qual área terei sucesso em breve?",
      "Como será meu relacionamento com os filhos?",
      "Vou encontrar o amor neste mês?",
      "Minha carreira está no caminho certo?",
      "Quando esperar uma promoção no trabalho?",
      "É um bom momento para investir em imóveis?",
      "O que o horóscopo diz sobre minha saúde?",
      "Vou fazer novos amigos este ano?",
      "Devo mudar de área profissional?",
      "Há risco de grandes gastos neste mês?",
      "Quando é melhor planejar férias?",
      "Terei sucesso com meu projeto criativo?",
      "Qual data é sortuda para assinar contrato?",
      "Quão compatível sou com meu parceiro?"
    ],
    modal: {
      me: {h: "Meus dados", dob:"Data de nascimento", place:"Local de nascimento", gender:"Gênero", time:"Hora de nascimento (opcional)", cancel:"Cancelar", save:"Salvar"},
      partner: {h:"Dados do parceiro", name:"Nome", dob:"Data de nascimento", place:"Local de nascimento", gender:"Gênero", time:"Hora de nascimento (opcional)", cancel:"Cancelar", save:"Salvar"},
      opts: {h:"Mais opções", num:"Numerologia", taro:"Tarô", china:"Horóscopo chinês", more:"Outra coisa", cancel:"Cancelar", save:"Salvar"},
    }
  },
  de: {
    qLbl: "Was ist Ihre Frage an den Astrologen?",
    me: "Meine Daten",
    partner: "Partnerdaten",
    opts: "Weitere Optionen",
    ask: "Antwort erhalten",
    ex: [
      "Soll ich mir nächste Woche einen BMW X5 kaufen?",
      "Was erwartet mich in der Beziehung mit einem neuen Partner?",
      "Wie wird sich meine Karriere dieses Jahr entwickeln?",
      "Wann ist der beste Zeitpunkt für ein neues Projekt?",
      "Soll ich dem Umzug zustimmen?",
      "Welche Monatsenergien sind für mich besonders wichtig?",
      "In welchem Bereich habe ich demnächst Erfolg?",
      "Wie läuft es mit den Kindern?",
      "Werde ich diesen Monat die Liebe finden?",
      "Ist mein Beruf der richtige für mich?",
      "Wann kann ich mit einer Beförderung rechnen?",
      "Ist jetzt ein guter Zeitpunkt für Immobilien-Investitionen?",
      "Was sagt das Horoskop über meine Gesundheit?",
      "Werde ich dieses Jahr neue Freunde finden?",
      "Soll ich das Berufsfeld wechseln?",
      "Sind hohe Ausgaben in diesem Monat riskant?",
      "Wann sollte ich am besten Urlaub planen?",
      "Werde ich mein Kreativprojekt umsetzen?",
      "Welches Datum ist gut zum Vertragsabschluss?",
      "Wie gut passe ich mit meinem Partner zusammen?"
    ],
    modal: {
      me: {h: "Meine Daten", dob:"Geburtsdatum", place:"Geburtsort", gender:"Geschlecht", time:"Geburtszeit (optional)", cancel:"Abbrechen", save:"Speichern"},
      partner: {h:"Partnerdaten", name:"Name", dob:"Geburtsdatum", place:"Geburtsort", gender:"Geschlecht", time:"Geburtszeit (optional)", cancel:"Abbrechen", save:"Speichern"},
      opts: {h:"Weitere Optionen", num:"Numerologie", taro:"Tarot", china:"Chinesisches Horoskop", more:"Sonstiges", cancel:"Abbrechen", save:"Speichern"},
    }
  },
  fr: {
    qLbl: "Quelle est votre question à l'astrologue ?",
    me: "Mes données",
    partner: "Données du partenaire",
    opts: "Options supplémentaires",
    ask: "Obtenir la réponse",
    ex: [
      "Dois-je acheter une BMW X5 la semaine prochaine ?",
      "Que m'attend-il dans la relation avec un nouveau partenaire ?",
      "Comment va évoluer ma carrière cette année ?",
      "Quand vaut-il mieux commencer un nouveau projet ?",
      "Dois-je accepter la mutation ?",
      "Quelles sont les énergies importantes ce mois-ci ?",
      "Dans quel domaine aurai-je du succès bientôt ?",
      "Comment se passent les relations avec les enfants ?",
      "Vais-je trouver l'amour ce mois-ci ?",
      "Ce métier est-il fait pour moi ?",
      "Quand attendre une promotion ?",
      "Est-ce le bon moment pour investir dans l'immobilier ?",
      "Que dit l'horoscope sur ma santé ?",
      "Vais-je me faire de nouveaux amis cette année ?",
      "Dois-je changer de domaine professionnel ?",
      "Y a-t-il un risque de grosses dépenses ce mois-ci ?",
      "Quand programmer des vacances ?",
      "Réussirai-je mon projet créatif ?",
      "Quelle date pour signer un contrat ?",
      "Quelle est ma compatibilité avec mon partenaire ?"
    ],
    modal: {
      me: {h: "Mes données", dob:"Date de naissance", place:"Lieu de naissance", gender:"Sexe", time:"Heure de naissance (optionnel)", cancel:"Annuler", save:"Enregistrer"},
      partner: {h:"Données du partenaire", name:"Nom", dob:"Date de naissance", place:"Lieu de naissance", gender:"Sexe", time
